config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'tests#index'
  resources :tests
  resources :questions
  resources :answers
  resources :student

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_one :result

  validates :answer, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :test
  has_many :answers
  accepts_nested_attributes_for :answers, :reject_if => lambda { |a| a[:answer].blank? }, :allow_destroy => true

  validates :question, presence: true
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :answer
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :questions
  accepts_nested_attributes_for :questions, :reject_if => lambda { |a| a[:question].blank? }, :allow_destroy => true

  #validates :name, presence: true
  #validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #validates :name, presence
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @answers = Answer.all
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      flash[:notice] = 'Ответ успешно создан'
      redirect_to @answer
    else
      render :action => 'new'
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to answer_url(@answer)
    else
      render 'edit'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy
    flash[:success] = 'Ответ успешно удален'

    redirect_to answers_path(@answer)
  end

  private

  def answer_params
    params.require(:answer).permit(:answer, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    # @answer = Answer.new
  end

  def new
    @question = Question.new
  end


  def create_question_with_test
    @question = Question.new
    @test = Test.find(params[:id])
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = 'Вопрос успешно создан'
      redirect_to @question
    else
      render :action => 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to question_url(@question)
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = 'Вопрос успешно удален'

    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:question, :test_id)
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController

  def tests
    @tests = Test.all
  end

  def questions
    test_id = params[:id]
    @test = Test.find test_id
    @questions = Question.where(test_id: @test)
  end


  def answers
    answer_id = params[:id]
    @answer = Answer.find answer_id
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = Test.all
  end

  def show
    @test = Test.find(params[:id])
  end

  # def new
  #   @test = Test.new
  # end

  def new
    @test = Test.new
      question = @test.questions.build
      question.answers.build
  end

  def create
    @test = Test.new(test_params)
    if @test.save
      flash[:notice] = 'Тест успешно создан'
      redirect_to @test
    else
      render :action => 'new'
    end
  end

  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])
    if @test.update(test_params)
      redirect_to test_url(@test)
    else
      render 'edit'
    end
  end

  def destroy
    @test = Test.find(params[:id])
    @test.destroy
    flash[:success] = 'Тест успешно удален'

    redirect_to tests_path
  end

  private

  def test_params
    params.require(:test).permit(:name, :description)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/answers/_form.html.erb
<%= form_for @answer, html: {class: 'form-horizontal col-sm-8'} do |f| %>
    <div class="form-group">
      <%= f.label :answer, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_area :answer, rows: 6, class: 'form-control' %>
      </div>
    </div>

    <div class="checkbox">
      <div class="col-sm-offset-2 col-sm-6">
        <input type="checkbox"> Is correct?
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit answer</h1>
<%= form_for @answer, html: {class: 'form-horizontal col-sm-8'} do |f| %>
    <div class="form-group">
      <%= f.label :answer, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_area :answer, rows: 6, autofocus: true, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/answers/index.html.erb
<div style="width: 900px; margin: auto">
  <h1>Answers</h1>

  <p>
    <%= link_to 'New answer', new_answer_path %>
  </p>

  <table class="table table-hover col-sm-12">
    <thead>
    <tr>
      <th class="col-sm-4">Answers</th>
      <th class="col-sm-2">Is correct</th>
      <th class="col-sm-2">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @answers.each do |answer| %>
        <tr>
          <td><%= answer.answer %></td>
          <td><input type="radio" name="blankRadio" id="blankRadio1" value="option1" aria-label="..."></td>
          <td>
            <%= link_to 'View, ', answer_path(answer) %>
            <%= link_to 'Edit, ', edit_answer_path(answer) %>
            <%= link_to 'Remove', answer_path(answer),
                        method: :delete,
                        data: {confirm: 'Вы действительно хотите удалить этот ответ?'} %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/answers/new.html.erb
<h1>Create new answer</h1>
<% provide :page_title, 'Новый ответ' %>

<%= render 'form' %>

app/views/answers/show.html.erb
<h1>Answer: "<%= @answer.answer %>"</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Tests', root_path, class: "navbar-brand" %>
      <%= link_to 'Questions', questions_path, class: "navbar-brand" %>
      <%= link_to 'Answers', answers_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-default navbar-btn" %>
            <%= link_to 'Log in', new_user_session_path, class: "btn btn-success navbar-btn" %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestingOfStudents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, html: {class: 'form-horizontal col-sm-8'} do |f| %>
    <div class="form-group">
      <%= f.label :question, class: 'col-sm-2 control-label' %>
      <div class="col-sm-6">
        <%= f.text_area :question, rows: 6, autofocus: true, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= f.submit 'Save', class: 'btn btn-success' %>
      </div>
    </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>
<% provide :page_title, 'Редактировать вопрос' %>

<%= render 'form' %>

app/views/questions/index.html.erb
<div style="width: 900px; margin: auto">
  <h1>Questions</h1>

  <p>
    <%= link_to 'New question', new_question_path %>
  </p>

  <table class="table table-hover col-sm-12">
    <thead>
    <tr>
      <th class="col-sm-4">Question</th>
      <th class="col-sm-2">Answers</th>
      <th class="col-sm-2">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @questions.each do |question| %>
        <tr>
          <td><%= question.question %></td>
          <td><%= question.answers.count %></td>
          <td>
            <%= link_to 'View, ', question_path(question) %>
            <%= link_to 'Edit, ', edit_question_path(question) %>
            <%= link_to 'Remove', question_path(question),
                        method: :delete,
                        data: {confirm: 'Вы действительно хотите удалить этот вопрос?'} %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/questions/new.html.erb
<h1>Create new question</h1>
<% provide :page_title, 'Новый вопрос' %>

<%= render 'form' %>

app/views/questions/show.html.erb
<h1>Question: "<%= @question.question %>"</h1>

<h3>Add new answer: "<%= @answer %>"</h3>

app/views/student/index_questions_by_test.html.erb
<div>
  Test: <%= link_to @test.name, tests_path(@test) %>
</div><br/>

<div>
  Description: <%= @test.description %>
</div><br/>

<div>
  Questions: <%= link_to @test.question, question_path(@test.id) %>
</div><br/>

<div>
  Answers: <%= link_to @questions.answer, question_path(@test.id) %>
</div><br/>